version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - GOPATH=/go/src
    ports:
      - 4000:4000
    tty: true
    volumes:
      - ./backend:/go/src/backend
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
      - ./frontend/package-lock.json:/frontend/package-lock.json
      - ./frontend/package.json:/frontend/package.json

  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d/go_movies.sql:/docker-entrypoint-initdb.d/go_movies.sql